import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import { Provider } from "jotai";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <ReactQueryProvider>
          <body className="pattern-leave bg-stone-950 text-stone-100 w-[100dvw] h-[100dvh]">
            {children}
          </body>
        </ReactQueryProvider>
      </Provider>
    </html>
  );
}
